### PR TITLE
Add `or`, `nor` filters to make more complex search queries

### PR DESCRIPTION
**Pull request by cewald**
Right now the opportunities to create a query are quiet limited.
I now added support for filters containing `or`, `or-not` and  `not-in` to the `elasticsearch` lib.

So you can filter queries like the following using the query-builder:
```js
query.applyFilter({ key: 'visibility', value: { in: [1, 2, 3] } })
query.applyFilter({ key: 'status', value: { nin: 1 } })
query.applyFilter({ key: 'status', value: { nin: [ 0, 1 ] } })
query.applyFilter({ key: 'price', value: { orGte: 14.99 } })
query.applyFilter({ key: 'special_price', value: { orLte: 20.99 } })
query.applyFilter({ key: 'color', value: { or: [ 12, 14 ] } })
query.applyFilter({ key: 'size', value: { nin: null } })
query.applyFilter({ key: 'sku', value: { nin: [ 'XXX-XXX-1', 'XXX-XXX-2' ] } })
```

WDYT, is this something that would be handy?

### CODE REVIEW

**Comment by gibkigonzo** [comment]
@cewald @pkarw  I'm thinking about mix this with https://github.com/DivanteLtd/storefront-query-builder/pull/3 Whole idea is that `applyFilter` should modify query based on filter from value. Can we have object with `filter: function` that returns queryChain? Same like here https://github.com/DivanteLtd/storefront-query-builder/pull/3/files#diff-13d602f7d04113162fedf4dd7b32f52bR13 
So we can refactor this to:
```
const baseFilters = {
  gt: ({ attribute, value }) => queryChain.filter('range', attribute, value)
  ...
}
```
Its same typing like:
```
    customFilters?: {
        [key: string]: Function;
    };
```
So we can have object with base filters and custom. Then we can merge
`filters = Object.assign({}, baseFilters, customFilter || {})`

Whats we get?
We can decouple applying filters logic. Which can gives us more readability (right now there are to much if and lets imagine that we want to add next filters).

**Comment by cewald** [comment]
@cewald @pkarw This is a really good idea. I agree with the too complex structure inside `buildQueryBodyFromSearchQuery` method.

I can try to add this if you like.

Anyway, I was going to suggest a modification to add a `applySort` method to handle more complex sorting as well. – If we me make changes like you suggested, it would be much easier to apply these additions.

**Comment by gibkigonzo** [comment]
Great! :) It would be great if you can do this. That is exactly why we need to decouple apply filters logic if we want to extend this in future, like adding `applySort`

**Comment by cewald** [comment]
I will close this in favour of #6

**Pull request closed without merging**
